Martinh/connect v1
wormhole-foundation/wormhole-docs pull request #109
Opened 2024-10-02 17:07 UTC by martin0995

### Description

Page related to Wormhole Connect migration to v.1.0

### Checklist

- [x] **Required** - I have added a label to this PR 🏷️
- [x] **Required** - I have run my changes through Grammarly
- [ ] If pages have been moved, I have created redirects in the `wormhole-mkdocs` repo

2024-10-02 17:27 UTC, albertov19 requested changes
LGTM! Great job, left some minor feedback

2024-10-02 17:27 UTC, albertov19 commented on build/applications/connect/v1-migration.md
> + - **Capitalized chain names** - all chain names, like "`ethereum`", must now be capitalized, such as "`Ethereum`", to maintain consistency with the rest of the Wormhole SDK
```suggestion
 - **Capitalized chain names** - all chain names, like `ethereum`, must now be capitalized, such as `Ethereum`, to maintain consistency with the rest of the Wormhole SDK
```

2024-10-02 17:27 UTC, albertov19 commented on build/applications/connect/v1-migration.md
> + - **Capitalized chain names** - all chain names, like "`ethereum`", must now be capitalized, such as "`Ethereum`", to maintain consistency with the rest of the Wormhole SDK
I believe this is not part of our standard of using "  plus the backtick

2024-10-02 17:27 UTC, albertov19 commented on build/applications/connect/v1-migration.md
> +#### Example: Old `tokensConfig`
I think these sections would be much better with the tabs "Old" and "New" 

Similar things for NTT etc

2024-10-02 17:34 UTC, eshaben reviewed
There are some things I don't love but for the sake of time we can sync on that stuff later so this is ready

2024-10-02 17:34 UTC, eshaben commented on build/applications/connect/.pages
> + - 'v1 Migration': v1-migration.md
I'd like to see the file name changed for longevity purposes as we discussed in Slack

2024-10-02 17:34 UTC, eshaben commented on build/applications/connect/v1-migration.md
> +    Solana: '<rpcUrl>',
```suggestion
    ethereum: 'INSERT_ETH_RPC_URL',
    solana: 'INSERT_SOLANA_RPC_URL',
  },
};

// Now (v1.0)
const config: WormholeConnectConfig = {
  rpcs: {
    Ethereum: 'INSERT_ETH_RPC_URL',
    Solana: 'INSERT_SOLANA_RPC_URL',
```

2024-10-02 17:34 UTC, eshaben commented on build/applications/connect/v1-migration.md
> +Key UI Changes:
```suggestion
Key UI changes:
```

2024-10-02 17:34 UTC, eshaben commented on build/applications/connect/v1-migration.md
> +???- tip "UI Properties"
I'd take this out of an expandable element since it's what the whole section is about

2024-10-02 17:34 UTC, eshaben commented on build/applications/connect/v1-migration.md
> +Important Details:
```suggestion
Important details:
```

2024-10-02 17:34 UTC, eshaben commented on build/applications/connect/v1-migration.md
> +Removed Config Keys:
```suggestion
Removed config keys:
```

2024-10-02 17:34 UTC, eshaben commented on build/applications/connect/v1-migration.md
> +    env: 'testnet',
```suggestion
  env: 'testnet',
```

2024-10-02 17:34 UTC, eshaben commented on build/applications/connect/v1-migration.md
> +    network: 'Testnet',
```suggestion
  network: 'Testnet',
```

2024-10-02 17:36 UTC, eshaben commented on build/applications/connect/v1-migration.md
> +#### Example: Old `tokensConfig`
Yes, just to reiterate, this should ideally be v1 and v0 instead of new and old

2024-10-02 17:39 UTC, eshaben commented on build/applications/connect/.pages
> + - 'v1 Migration': v1-migration.md
Just to be clear, should be `migration.md` or `upgrade.md` the `v1 Migration` part is fine for now

2024-10-02 17:43 UTC, eshaben commented on build/applications/connect/v1-migration.md
> +Key Changes:
```suggestion
Key changes:
```

oops missed this one

2024-10-03 02:31 UTC, eshaben commented on build/applications/connect/upgrade.md
> +=== "v1.0+"
These tab names are inconsistent, some of them say `v1.0+` and others say `v1.0` (without the `+`) - To make it applicable to all minor releases of v1, you could do `v1.x` - similarly, you could do `v0.x` for v0

2024-10-03 02:31 UTC, eshaben commented on build/applications/connect/upgrade.md
> +    const config: WormholeConnectConfig = {
The spacing is 4 now on some of these code snippets. This can always be addressed down the road if in a time pinch to ship this

2024-10-03 08:42 UTC, albertov19 submitted a review, later dismissed

2024-10-03 09:04 UTC, albertov19 approved these changes
LGTM 🚢

2024-10-03 09:04 UTC, merged

2024-10-03 09:24 UTC, PaulineAnnBar commented on build/applications/connect/v1-migration.md
> +In version 1.0, chain names are now consistent with the `Chain` type from the [Wormhole TypeScript SDK](https://github.com/wormhole-foundation/wormhole-sdk-ts){target=\_blank}, and must be capitalize
that's good! What about testnet? Have we agree to a a format so we avoid confusion?

2024-10-03 10:03 UTC, martin0995 commented on build/applications/connect/v1-migration.md
> +In version 1.0, chain names are now consistent with the `Chain` type from the [Wormhole TypeScript SDK](https://github.com/wormhole-foundation/wormhole-sdk-ts){target=\_blank}, and must be capitalize
All the chain names (Mainnet and Testnet) are included in the link provided (Line 76):
https://github.com/wormhole-foundation/wormhole-sdk-ts/blob/fa4ba4bc349a7caada809f209090d79a3c5962fe/core/base/src/constants/chains.ts#L12-L66