token bridge faq
wormhole-foundation/wormhole-docs pull request #164
Opened 2024-12-05 15:08 UTC by ilariae

### Description

updated contracts faq

### Checklist

- [x] **Required** - I have added a label to this PR 🏷️
- [x] **Required** - I have run my changes through Grammarly
- [ ] If pages have been moved, I have created redirects in the `wormhole-mkdocs` repo

2024-12-05 19:09 UTC, dawnkelly09 requested changes
Couple little nits. Thanks!

2024-12-05 19:09 UTC, dawnkelly09 commented on build/contract-integrations/faqs.md
> +## Is there a way to use NTT tokens with chains that don’t currently support NTT?
```suggestion
## Is there a way to use NTT tokens with chains that don't currently support NTT?
```

2024-12-05 19:09 UTC, dawnkelly09 commented on build/contract-integrations/faqs.md
> +Yes, NTT tokens can be used with chains that do not support NTT by leveraging the [token bridge](/docs/learn/messaging/token-bridge/){target=\_blank}. For example:
```suggestion
Yes. NTT tokens can be used with chains that do not support NTT by leveraging the [token bridge](/docs/learn/messaging/token-bridge/){target=\_blank}. For example:
```

2024-12-05 19:09 UTC, dawnkelly09 commented on build/contract-integrations/faqs.md
> +- **Wrapped token scenario** - a token, such as W token, can be bridged to non-NTT networks using the token bridge. When the token is bridged to a chain like Sui, a wrapped version of the token is cr
```suggestion
- **Wrapped token scenario** - a token, such as the W token, can be bridged to non-NTT networks using the token bridge. When the token is bridged to a chain like Sui, a wrapped version of the token is created (e.g., Wrapped W token)
```

2024-12-06 05:56 UTC, eshaben commented on build/contract-integrations/faqs.md
> +- **Unwrapping requirement** - tokens bridged using the token bridge cannot be directly transferred to NTT-supported chains. To transfer them, they must first be unwrapped on the non-NTT chain and th
```suggestion
- **Unwrapping requirement** - tokens bridged using the Token Bridge cannot be directly transferred to NTT-supported chains. To transfer them, they must first be unwrapped on the non-NTT chain and then transferred via the appropriate mechanism
```

2024-12-06 05:56 UTC, eshaben commented on build/contract-integrations/faqs.md
> +- **Messaging consistency** - the token bridge exclusively uses Wormhole messaging, ensuring consistent communication across all chains, whether or not they support NTT
```suggestion
- **Messaging consistency** - the Token Bridge exclusively uses Wormhole messaging, ensuring consistent communication across all chains, whether or not they support NTT
```

2024-12-06 14:46 UTC, dawnkelly09 approved these changes
nice work!

2024-12-06 14:49 UTC, merged