Added hub and spoke description
wormhole-foundation/wormhole-docs pull request #172
Opened 2024-12-19 12:19 UTC by martin0995

### Description

Adds `hub-and-spoke` description and contrasts with `burn-and-mint` logic under the NTT token deployment on EVM.

### Checklist

- [x] **Required** - I have added a label to this PR 🏷️
- [x] **Required** - I have run my changes through Grammarly
- [ ] If pages have been moved, I have created redirects in the `wormhole-mkdocs` repo

2024-12-19 13:10 UTC, evgeniko commented on build/contract-integrations/native-token-transfers/deployment-process/deploy-to-evm.md
> +A central hub chain (e.g., Ethereum) manages the total token supply in hub-and-spoke mode. Other chains (spokes) use wrapped tokens representing burned tokens from the hub chain.
Spoke chains dont use wrapped tokens. The deployed tokens are native to the respective chain, but are burned or minted when transferred to the Hub chain

2024-12-19 13:11 UTC, evgeniko commented on build/contract-integrations/native-token-transfers/deployment-process/deploy-to-evm.md
> +For example, when transferring tokens from Ethereum (hub) to Polygon (spoke), the NTT Manager burns Ethereum tokens. In contrast, wrapped tokens representing the same amount are minted on Polygon. Si
thats not correct. Tokens are not burned on the hub-chain. They are locked when transferring to the spoke chains. Tokens are only burned or minted on the spoke chains. 
Also please correct, that there are no wrapped tokens when deploying with NTT

2024-12-19 13:12 UTC, evgeniko commented on build/contract-integrations/native-token-transfers/deployment-process/deploy-to-solana.md
> +Tokens used in Wormhole’s NTT can operate in burning mode or as hub chain tokens in hub-and-spoke mode. These modes differ in how tokens are managed and configured for cross-chain transfers.
I would delete this comment, cause it does not bring any value to the reader. Also, since NTT is an open framework, the builder can choose any other modes as well. These 2 modes are just the first 2 supported by the NTT CLI

2024-12-19 13:14 UTC, evgeniko commented on build/contract-integrations/native-token-transfers/deployment-process/deploy-to-solana.md
> +### Hub Chain Requirements
please adjust accordingly to the comment in the deploy-to-evm file.
Maybe we actually dont have the same comment twice, but  have this explainer in another section? Maybe in the FAQs ?

2024-12-20 13:29 UTC, evgeniko commented on build/contract-integrations/native-token-transfers/deployment-process/deploy-to-evm.md
> +    Beyond deploying the ERC20 token, no additional deployment steps are necessary on the hub chain. Steps like setting mint authority apply only to spoke chains.
This might be confusing to folks that already have an ERC20 token deployed. Lets maybe rather stress, that the only requirement is to have an ERC20 token and that also an existing one can be used

2024-12-20 15:36 UTC, dawnkelly09 requested changes
Some grammarly things

2024-12-20 15:36 UTC, dawnkelly09 commented on build/contract-integrations/native-token-transfers/deployment-process/deploy-to-evm.md
> + - **Burn-and-Mint** - tokens must implement custom `mint` and `burn` functions, allowing each chain to independently manage token issuance
```suggestion
 - **Burn-and-Mint** - tokens must implement custom `mint` and `burn` functions, allowing each chain to manage token issuance independently
```

2024-12-20 15:36 UTC, dawnkelly09 commented on build/contract-integrations/native-token-transfers/deployment-process/deploy-to-solana.md
> +For hub chain deployments on Solana, the token can be either an SPL or Token2022 token. No additional configuration, such as setting the mint authority, is required for hub chain tokens.
```suggestion
For hub chain deployments on Solana, the token can be either an SPL or Token2022. Hub chain tokens do not require additional configuration, such as setting the mint authority.
```

2024-12-20 16:39 UTC, dawnkelly09 submitted a review, later dismissed
🚀

2024-12-23 08:40 UTC, eshaben commented on build/contract-integrations/native-token-transfers/deployment-process/deploy-to-evm.md
> + - **Hub-and-Spoke** - tokens only need to be ERC20 compliant, with the hub chain acting as the source of truth for supply consistency
```suggestion
 - **Burn-and-mint** - tokens must implement custom `mint` and `burn` functions, allowing each chain to manage token issuance independently
 - **Hub-and-spoke** - tokens only need to be ERC20 compliant, with the hub chain acting as the source of truth for supply consistency
```

2024-12-23 15:50 UTC, eshaben approved these changes
LGTM!

2024-12-23 15:54 UTC, merged