Ilariae/ftintro
wormhole-foundation/wormhole-docs pull request #33
Opened 2024-08-28 10:45 UTC by ilariae

### Description

Fast Transfers overview page

### Checklist

- [x] **Required** - I have added a label to this PR 🏷️
- [x] **Required** - I have run my changes through Grammarly
- [ ] If pages have been moved, I have created redirects in the `wormhole-mkdocs` repo

2024-08-29 17:38 UTC, albertov19 requested changes
Looking good! Getting there! Left some more comments!

2024-08-29 17:38 UTC, albertov19 commented on learn/fast-transfers.md
> +Fast Transfers addresses these challenges by introducing an innovative solution that ensures quick and efficient cross-chain liquidity movement. The protocol is built on Solana, which was chosen for
```suggestion
To address such issues, Wormhole offers users/developers Fast Transfers. It introduces an innovative solution that ensures quick and efficient cross-chain liquidity movement. The protocol is built on Solana, which was chosen for its fast finality and low transaction costs. The unique feature that sets Fast Transfers apart is its aggregated auction mechanism, which operates within a hub-and-spoke model. In this model, Solana acts as the central hub, concentrating liquidity and enabling rapid transfers to destination chains.
```

2024-08-29 17:38 UTC, albertov19 commented on learn/fast-transfers.md
> +The core of Fast Transfers lies in its auction mechanism, where solvers and market makers compete to provide the best rates for cross-chain transactions. This competition and the liquidity aggregatio
I like this structure much better but mentioning the auction mechanism here feels repetitive

2024-08-29 17:38 UTC, albertov19 commented on learn/fast-transfers.md
> +The core of Fast Transfers lies in its auction mechanism, where solvers and market makers compete to provide the best rates for cross-chain transactions. This competition and the liquidity aggregatio
```suggestion
In Fast Transfers auctions, solvers and market makers compete to provide the best rates for cross-chain transactions. This competition and the liquidity aggregation layer allow the protocol to bypass the delays associated with traditional cross-chain transfers. By aggregating liquidity and employing an effective auction system, Fast Transfers significantly reduces wait times. It is a solid solution for developers building applications that require fast and reliable cross-chain asset transfers.
```

2024-08-29 17:38 UTC, albertov19 commented on learn/fast-transfers.md
> +- **Hub** - the central node where all resources—data, assets, or information—are aggregated and managed. The hub handles the distribution to the spokes, acting as a central point of processing and c
```suggestion
- **Hub** - the central node where all resources, data, assets, or information are aggregated and managed. The hub handles the distribution to the spokes, acting as a central point of processing and coordination
```

2024-08-29 17:38 UTC, albertov19 commented on learn/fast-transfers.md
> +This model is highly efficient because it centralizes control and reduces the complexity of direct interactions between each endpoint. Instead of managing multiple direct connections, each spoke only
```suggestion
This model is highly efficient because it aggregates control and reduces the complexity of direct interactions between each endpoint. Instead of managing multiple direct connections, each spoke only needs to connect to the hub, simplifying the overall system.
```

2024-08-29 17:38 UTC, albertov19 commented on learn/fast-transfers.md
> +This model is highly efficient because it centralizes control and reduces the complexity of direct interactions between each endpoint. Instead of managing multiple direct connections, each spoke only
Centralization is a word we tend to avoid haha

2024-08-29 17:38 UTC, albertov19 commented on learn/fast-transfers.md
> +- **Hub chain** - Solana is the central hub where all liquidity is concentrated. Solana was selected as the hub due to its fast finality, low transaction costs, and strong support for the [Cross-Chai
Having another bullet for hub chain and spoke chain feels repetitive. I would remove and merge with the list from before

2024-08-29 17:38 UTC, albertov19 commented on learn/fast-transfers.md
> +1. **Hub chain** - the transfer process begins by moving assets from the source chain to the hub chain, Solana. Here, liquidity is concentrated, and the auction process takes place
```suggestion
1. **Liquidity aggregation** - the transfer process begins by moving assets from the source chain (a spoke) to the hub chain, Solana. Here, liquidity is concentrated, and the auction process takes place
```

2024-08-29 17:38 UTC, albertov19 commented on learn/fast-transfers.md
> +2. **Auction process** - once the assets reach Solana, an auction is initiated on the hub chain. Solvers, who are market participants, bid to provide the best possible rate for the transfer. The winn
```suggestion
2. **Auction process** - once the assets reach Solana, an auction is initiated on the hub chain. Solvers, who are market participants, bid to provide the best possible rate for the transfer. The winning solver executes the swap and facilitates the transfer to the destination chain via:
```

2024-08-29 17:38 UTC, albertov19 commented on learn/fast-transfers.md
> +3. **CCTP** - the protocol uses the [Cross-Chain Transfer Protocol (CCTP)](/learn/messaging/cctp/){target=\_blank} to manage the movement of assets from the hub chain. CCTP handles the burning of tok
```suggestion
        -  **CCTP** - the protocol uses the [Cross-Chain Transfer Protocol (CCTP)](/learn/messaging/cctp/){target=\_blank} to manage the movement of assets from the hub chain. CCTP handles the burning of tokens on the source chain and the minting of equivalent tokens on the destination chain, ensuring the integrity of the transfer process
```

2024-08-29 17:38 UTC, albertov19 commented on learn/fast-transfers.md
> +3. **CCTP** - the protocol uses the [Cross-Chain Transfer Protocol (CCTP)](/learn/messaging/cctp/){target=\_blank} to manage the movement of assets from the hub chain. CCTP handles the burning of tok
Please check that this renders well. But I removed the number because it is either CCTP or NTT

2024-08-29 17:38 UTC, albertov19 commented on learn/fast-transfers.md
> +4. **[NTT (Native Token Transfers)](/learn/messaging/ntt/ntt-overview/){target=\_blank}** - for chains that do not support CCTP, Fast Transfers employs NTT messages. In this case, USDC is locked on S
```suggestion
        - **[NTT (Native Token Transfers)](/learn/messaging/ntt/ntt-overview/){target=\_blank}** - for chains that do not support CCTP, Fast Transfers employs NTT messages. In this case, USDC is locked on Solana, and an NTT message is sent to the destination chain, triggering the transfer of an equivalent value of tokens
```

2024-08-29 17:38 UTC, albertov19 commented on learn/fast-transfers.md
> +#### Overview of the Hub and Spoke Model
We avoid titles with #### - I would remove this title as you are already speaking about the Hub and Spoke

2024-08-29 17:38 UTC, albertov19 commented on learn/fast-transfers.md
> +### How It Works
I would put this a bit higher up. Maybe provide the key steps of how it works and then go into detail on each? Another thing you don't mention is that with CCTP USDC is used as the base asset, so there is also USDC liquidity required to move assets etc

2024-08-29 17:38 UTC, albertov19 commented on learn/fast-transfers.md
> +1. **Initiation** - users initiate a transfer through the Fast Transfers protocol, either via a user interface (UI) or directly on-chain. They can choose between a standard transfer, which waits for
```suggestion
1. **Initiation** - users initiate a transfer through the Fast Transfers protocol, either via a user interface (UI) or directly on-chain. They can choose between a standard transfer, which waits for finality on the sending chain, or a Fast Transfer, which triggers the auction process. For Fast Transfers, users specify a maximum fee they are willing to pay and a deadline by which the auction must start. This ensures that the process is both cost-effective and timely
```

2024-08-29 17:38 UTC, albertov19 commented on learn/fast-transfers.md
> +2. **Auction** - the auction begins on the Solana network when a user requests a fast transfer. Solvers monitor the network for these requests and initiate an auction by placing an offer to fulfill t
```suggestion
2. **Auction** - the auction begins on the Solana network when a user requests a Fast Tansfer. Solvers monitor the network for these requests and initiate an auction by placing an offer to fulfill the transfer at or below the user’s specified maximum fee. To start the auction, the solver must transfer the amount of USDC requested by the user (X USDC) plus a small security deposit to the Fast Transfer hub on Solana. This deposit acts as a commitment to the process
```

2024-08-29 17:38 UTC, albertov19 commented on learn/fast-transfers.md
> +2. **Auction** - the auction begins on the Solana network when a user requests a fast transfer. Solvers monitor the network for these requests and initiate an auction by placing an offer to fulfill t
When do we put caps, and when do we not?

2024-08-29 17:38 UTC, albertov19 commented on learn/fast-transfers.md
> +3. **Competition** - once the auction is initiated, other solvers can participate by submitting lower bids in a reverse Dutch auction. The goal is to provide end users with the best possible rate. If
Add link to an explainer of Dutch auction?

2024-08-29 17:38 UTC, albertov19 commented on learn/fast-transfers.md
> +Upon successful completion, the Fast Transfer hub sends the X USDC to the user’s destination wallet, and the solver receives their security deposit back along with the fee for the transfer
Remove the space here so that the "Upon successful" is not in a next line. Nothing changes tho

2024-08-29 17:38 UTC, albertov19 commented on learn/fast-transfers.md
> +### Solution Provided by Fast Transfers
Unsure if this is good here or just add it to the intro? It is good but having the solutions near the end is a bit of sad haha

2024-08-29 17:38 UTC, albertov19 commented on learn/fast-transfers.md
> +### Liquidity Fragmentation
This can be added to the intro. Problem statement and solution should be near the top

2024-09-02 13:06 UTC, albertov19 approved these changes
LGTM

2024-09-02 13:06 UTC, albertov19 commented on learn/fast-transfers.md
> +The key component of Fast Transfers is its aggregated auction mechanism, where solvers and market makers compete to offer the best rates for cross-chain transactions. This competitive environment ens
```suggestion
The key component of Fast Transfers is its aggregated auction mechanism, where solvers/market makers compete to offer the best rates for cross-chain transactions. This competitive environment ensures optimal pricing and efficient execution of transfers, significantly reducing wait times compared to traditional cross-chain methods.
```

2024-09-02 13:14 UTC, albertov19 approved these changes
Looks good! Would be great to create a follow up ticket to add some diagrams etc

2024-09-02 13:16 UTC, albertov19 submitted a review, later dismissed

2024-09-03 17:58 UTC, dawnkelly09 approved these changes
This evolved really nicely. Thank you for your work!

2024-09-03 18:11 UTC, eshaben reviewed
Did a quick scan and just found one minor thing

2024-09-03 18:11 UTC, eshaben commented on learn/fast-transfers.md
> +- **New Revenue Streams** - by facilitating fast transfers, solvers can earn fees on each transfer they process. This creates a new source of income and allows solvers to capitalize on the growing vo
The capitalization of these list items just needs to be fixed so only the first word is capitalized

2024-09-03 19:17 UTC, eshaben approved these changes
Beautiful! Thanks!

2024-09-03 19:17 UTC, merged