Martinh/cross chain token contracts
wormhole-foundation/wormhole-docs pull request #50
Opened 2024-09-02 16:33 UTC by martin0995

### Description

Cross-chain Token Contracts page.

### Checklist

- [x] **Required** - I have added a label to this PR 🏷️
- [x] **Required** - I have run my changes through Grammarly
- [ ] If pages have been moved, I have created redirects in the `wormhole-mkdocs` repo

2024-09-03 19:25 UTC, dawnkelly09 requested changes
I left some comments about issues I had trying to start the project. Happy to look at the rest once I can get past there. :-)

2024-09-03 19:25 UTC, dawnkelly09 commented on tutorials/messaging/cross-chain-token-contracts.md
> +    ```bash
Also, this `create-foundry-project` looks unmaintained and fairly old. It's not the way Foundry docs tell users to make a new project: https://book.getfoundry.sh/projects/creating-a-new-project

When I run this npx package on my machine, I get errors in the terminal because it's trying to set the default branch as `master` which is not inclusive language, etc for a demo. Unless there is a good reason for using this package vs what is in Foundry docs, I don't think we should.

2024-09-04 18:50 UTC, eshaben commented
@martin0995 looks like this is ready for review again, so I'll re-request Dawn's review. But please just make sure that you request a review again on GitHub. You can do this from the right side menu at the top under **Reviewers** just click the little refresh button that appears there

2024-09-04 20:03 UTC, dawnkelly09 requested changes
I made it much further this time but I think something is still missing from the steps/instructions (see comments).

2024-09-04 20:03 UTC, dawnkelly09 commented on tutorials/messaging/cross-chain-token-contracts.md
> +    1. Create a new file named `deploy.ts` in the `/src` directory:
Okay! This time, I made it all the way to here before I ran into problems, so hooray for progress! There is something missing here, I think. I created my `deploy.ts` file and then started adding code following the next few steps and I have some errors popping up:
- Cannot find module 'dotenv' or its corresponding type declarations.ts(2307)
- Cannot find module 'readline-sync' or its corresponding type declarations.ts(2307)
- Cannot find name 'ChainConfig'.ts(2304)
- Cannot find name 'sourceChain'.ts(2304)
- Cannot find name 'targetChain'.ts(2304)

Please take a look at this and see if something needs added. Is this supposed to be typescript? Does typescript come bundled in Foundry somehow (I have no idea)? Otherwise, how is this user getting the typescript into the project? Are we missing some dependency we should tell them to install?

2024-09-05 16:00 UTC, dawnkelly09 approved these changes
Bravo, Martin!!! I know I was so picky but this worked beautifully and now we know even a junior dev can successfully build it with these instructions. Great work!

2024-09-06 03:56 UTC, eshaben reviewed
Great job! Really nicely done ✨ 

Side note: I opened a PR in the wormhole-mkdocs repository to fix the terminal header that was extending out to the right too far

2024-09-06 03:56 UTC, eshaben commented on tutorials/messaging/cross-chain-token-contracts.md
> +It's important to note that this tutorial leverages [Wormhole's TokenBridge](https://github.com/wormhole-foundation/wormhole/blob/6130bbb6f456b42b789a71f7ea2fd049d632d2fb/ethereum/contracts/bridge/To
This should either be Token Bridge or `TokenBridge` - please check all instances

2024-09-06 03:56 UTC, eshaben commented on tutorials/messaging/cross-chain-token-contracts.md
> +        - Enter the source chain ID
these should be numbered (which will result in a, b, c... for nested ordered lists) since this happens sequentially

2024-09-06 03:56 UTC, eshaben commented on tutorials/messaging/cross-chain-token-contracts.md
> +    This SDK includes the `TokenSender` and `TokenReceiver` abstract classes, which simplify sending and receiving tokens across chains.
```suggestion
    To ease development, we'll use the Wormhole Solidity SDK, which provides useful helpers for cross-chain development. This SDK includes the `TokenSender` and `TokenReceiver` abstract classes, which simplify sending and receiving tokens across chains.
```

It just looked a little off to me

2024-09-06 03:56 UTC, eshaben commented on tutorials/messaging/cross-chain-token-contracts.md
> +Here’s a breakdown of what happens in each step:
```suggestion
Here’s a breakdown of what happens in each step of the `sendCrossChainDeposit` function:
```

Just for extra clarity. I was skimming and that's probably my problem, but I thought this was just referencing the above steps and not the specific function

2024-09-06 03:56 UTC, eshaben commented on tutorials/messaging/cross-chain-token-contracts.md
> +??? tip "Understanding the `TokenReceived` Struct"
Nice!

2024-09-06 03:56 UTC, eshaben commented on tutorials/messaging/cross-chain-token-contracts.md
> +5. **Compile your smart contracts** - compile your smart contracts using Foundry. This ensures that your contracts are up-to-date and ready for deployment
```suggestion
3. **Compile your smart contracts** - compile your smart contracts using Foundry. This ensures that your contracts are up-to-date and ready for deployment
```

2024-09-06 03:56 UTC, eshaben commented on tutorials/messaging/cross-chain-token-contracts.md
> +3. **Write the deployment script** - you’ll need a script to automate the deployment of your contracts. Let’s create the deployment script
```suggestion
4. **Write the deployment script** - you’ll need a script to automate the deployment of your contracts. Let’s create the deployment script
```

2024-09-06 03:56 UTC, eshaben commented on tutorials/messaging/cross-chain-token-contracts.md
> +    3. Load and select the chains for deployment:
```suggestion
    4. Load and select the chains for deployment:
```

2024-09-06 03:56 UTC, eshaben commented on tutorials/messaging/cross-chain-token-contracts.md
> +    3. Load and select the chains for deployment:
WIll you please check all the steps in this guide just to make sure they're all in sequential order? I know it renders properly, but this will just avoid any potential confusion for anyone else who edits this file in the future

2024-09-06 03:56 UTC, eshaben commented on tutorials/messaging/cross-chain-token-contracts.md
> +        The scripts establish a connection to the blockchain using a provider and create a wallet instance using a private key. This wallet is responsible for signing the deployment transaction on th
I'm not a fan of this text after the colon, because I feel like the colon indicates that you're going to tell them what to do (like provide a set of steps or show them code) and it's just more explainer text. So I think this can be moved after the script like the other steps

2024-09-06 03:56 UTC, eshaben commented on tutorials/messaging/cross-chain-token-contracts.md
> +            ```
This looks a bit weird for the reasons I mentioned in my previous comment:

> I'm not a fan of this text after the colon, because I feel like the colon indicates that you're going to tell them what to do (like provide a set of steps or show them code) and it's just more explainer text.

<img width="750" alt="Screenshot 2024-09-05 at 11 48 29 PM" src="https://github.com/user-attachments/assets/ec3885f2-354d-4dc1-807d-60abca688f85">

2024-09-06 03:56 UTC, eshaben commented on tutorials/messaging/cross-chain-token-contracts.md
> +3. **Verify the transaction** - after running the script, you should see a confirmation message with the transaction hash. You can use this transaction hash to check the transfer status on the respec
```suggestion
2. **Follow the prompts** - the script will guide you through selecting the source and target chains and entering the necessary details for the token transfer. Once you provide all the required information, the script will initiate the token transfer

3. **Verify the transaction** - after running the script, you should see a confirmation message with the transaction hash. You can use this transaction hash to check the transfer status on the respective blockchain explorers
```

No punctuation at the end of list items

2024-09-06 03:56 UTC, eshaben commented on tutorials/messaging/cross-chain-token-contracts.md
> +If you'd like to explore the complete project or need a reference while following this tutorial, you can find the complete codebase in the [GitHub repository](https://github.com/martin0995/cross-chai
```suggestion
If you'd like to explore the complete project or need a reference while following this tutorial, you can find the complete codebase in the [Cross-Chain Token Transfers GitHub repository](https://github.com/martin0995/cross-chain-token-transfers){target=\_blank}. The repository includes all the scripts, contracts, and configurations needed to deploy and transfer tokens across chains using the Wormhole protocol.
```

2024-09-06 03:56 UTC, eshaben commented on tutorials/messaging/cross-chain-token-contracts.md
> +        ???- example "Save Deployment Details"
I'd just use the code admonition for this

2024-09-06 14:37 UTC, eshaben commented
@martin0995 can you please resolve the merge conflicts?

2024-09-06 14:43 UTC, eshaben reviewed
Almost there

2024-09-06 14:43 UTC, eshaben commented on tutorials/messaging/cross-chain-token-contracts.md
> +    3. Load and select the chains for deployment:
There are two 3s back to back

2024-09-06 14:43 UTC, eshaben commented on tutorials/messaging/cross-chain-token-contracts.md
> +
two 4s back to back

2024-09-06 14:43 UTC, eshaben commented on .pages
>   - tutorials
This order should be:

- build
- infrastructure
- tutorials
- learn

2024-09-06 15:37 UTC, eshaben approved these changes
LGTM! 🚢

2024-09-06 15:37 UTC, merged