Ilariae/how to solver
wormhole-foundation/wormhole-docs pull request #55
Opened 2024-09-05 13:54 UTC by ilariae

### Description

how to be a solver content
the two links missing for matching engine and token router direct to the next page I'm gonna make, I will add them in that pr 

### Checklist

- [x] **Required** - I have added a label to this PR 🏷️
- [x] **Required** - I have run my changes through Grammarly
- [ ] If pages have been moved, I have created redirects in the `wormhole-mkdocs` repo

2024-09-06 10:41 UTC, albertov19 requested changes
Left some comments 😄

2024-09-06 10:41 UTC, albertov19 commented on build/fast-transfers/how-to-solver.md
> +In Fast Transfers, solvers ensure efficient cross-chain transfers through a competitive auction process on the Matching Engine. The auction consists of four key steps: <!-- link to matching engine --
```suggestion
In [Fast Transfers](/learn/messaging/fast-transfers/){target=\_blank}, solvers ensure efficient cross-chain transfers through a competitive auction process on the Matching Engine. The auction consists of four key steps: <!-- link to matching engine -->
```

2024-09-06 10:41 UTC, albertov19 commented on build/fast-transfers/how-to-solver.md
> +In Fast Transfers, solvers ensure efficient cross-chain transfers through a competitive auction process on the Matching Engine. The auction consists of four key steps: <!-- link to matching engine --
Note that the URL I put is expecting Fast Transfer to be under Messaging

2024-09-06 10:41 UTC, albertov19 commented on build/fast-transfers/how-to-solver.md
> +### Send transactions to verify signatures and post VAA
```suggestion
### Send Transactions to Verify Signatures and Post VAA
```

2024-09-06 10:41 UTC, albertov19 commented on build/fast-transfers/how-to-solver.md
> +When users interact with Token Routers to transfer assets faster than finality to another chain, they place an order that is processed by the Matching Engine. <!-- link to token routers -->
Do we have a URL to Token Routers? I think we were working on having a page with the contracts or something?

2024-09-06 10:41 UTC, albertov19 commented on build/fast-transfers/how-to-solver.md
> +When users interact with Token Routers to transfer assets faster than finality to another chain, they place an order that is processed by the Matching Engine. <!-- link to token routers -->
Similar comment on Matching Engine. What is it? Where can we read more about it? Maybe adding something in the Learn section about the Matching Engine is necessary?

2024-09-06 10:41 UTC, albertov19 commented on build/fast-transfers/how-to-solver.md
> +The [VAA (Verified Action Approval)](/learn/infrastructure/vaas/){target=\_blank} is a message that acts as an IOU (I owe you) for the solver when the auction is settled. The Wormhole Spy or a [relay
Add URL to Wormhole Spy?

2024-09-06 10:41 UTC, albertov19 commented on build/fast-transfers/how-to-solver.md
> +To read VAAs on Solana, someone must verify the signatures and post the VAA to a Solana account using the Wormhole Core Bridge. This is done through the Wormhole JS SDK.
I think we call it Wormhole TS SDK and we should add a link

2024-09-06 10:41 UTC, albertov19 commented on build/fast-transfers/how-to-solver.md
> +### Send transaction to place initial offer
```suggestion
### Send Transaction to Place Initial Offer
```

2024-09-06 10:41 UTC, albertov19 commented on build/fast-transfers/how-to-solver.md
> +--8<-- 'code/build/fast-transfers/how-to-solver/send-tx-2.js'
this code will for sure fail because there is a bunch of variables that are not being initialized properly like ":Keypair", "MatchingEngineProgram"

Unclear what we should do here

2024-09-06 10:41 UTC, albertov19 commented on build/fast-transfers/how-to-solver.md
> +- Listen to a Solana web socket connection to find the account when the initial offer is placed
```suggestion
- Listening to a Solana web socket connection to find the account when the initial offer is placed
```

2024-09-06 10:41 UTC, albertov19 commented on build/fast-transfers/how-to-solver.md
> +- Use the fast VAA bytes to compute its hash and derive its auction account address
```suggestion
- Using the fast VAA bytes to compute its hash and derive its auction account address
```

2024-09-06 10:41 UTC, albertov19 commented on build/fast-transfers/how-to-solver.md
> +- Use the fast VAA bytes to compute its hash and derive its auction account address
Would be great to add more info on how you do this

2024-09-06 10:41 UTC, albertov19 commented on build/fast-transfers/how-to-solver.md
> +--8<-- 'code/build/fast-transfers/how-to-solver/auction-1.js'
Similar comments that those on the previous snippet

2024-09-06 10:41 UTC, albertov19 commented on build/fast-transfers/how-to-solver.md
> +### Send transactions to verify signatures and post VAA
```suggestion
### Send Transactions to Verify Signatures and Post VAA
```

2024-09-06 10:41 UTC, albertov19 commented on build/fast-transfers/how-to-solver.md
> +Anyone can post the VAAs on Solana to read and verify VAAs using Wormhole Core Bridge instructions. This is typically done using the Wormhole JS SDK, as shown below:
Wormhole TS SDK

2024-09-06 10:41 UTC, albertov19 commented on build/fast-transfers/how-to-solver.md
> +### Send transaction to settle complete auction
```suggestion
### Send Transaction to Settle Complete Auction
```

2024-09-06 10:41 UTC, albertov19 commented on build/fast-transfers/how-to-solver.md
> +--8<-- 'code/build/fast-transfers/how-to-solver/mainnet-addresses.js'
Would it be better to put this in a table?

2024-09-06 14:11 UTC, ilariae commented on build/fast-transfers/how-to-solver.md
> +To read VAAs on Solana, someone must verify the signatures and post the VAA to a Solana account using the Wormhole Core Bridge. This is done through the Wormhole JS SDK.
are you sure it should be TS? isn't this javascript?

2024-09-06 15:53 UTC, albertov19 commented on build/fast-transfers/how-to-solver.md
> +To read VAAs on Solana, someone must verify the signatures and post the VAA to a Solana account using the Wormhole Core Bridge. This is done through the Wormhole JS SDK.
Well we are documenting the Wormhole Typescript SDK. SO I would think so. TS and JS are compatible

2024-09-06 16:55 UTC, dawnkelly09 commented on build/fast-transfers/how-to-solver.md
> +To read VAAs on Solana, someone must verify the signatures and post the VAA to a Solana account using the Wormhole Core Bridge. This is done through the Wormhole JS SDK.
TypeScript, not Typescript, but otherwise, yes.

2024-09-09 12:49 UTC, ilariae commented
need to finish a couple of things but note that I move the Fast Transfers from the learn section into Learn > messaging

2024-09-10 10:09 UTC, albertov19 approved these changes
LGTM!

2024-09-10 10:09 UTC, albertov19 commented on build/fast-transfers/how-to-solver.md
> +| Component               | chainId | Address                                      | Constructor Arguments            |
For future reference, it is good to put all variables in the yaml file

2024-09-10 16:46 UTC, dawnkelly09 requested changes
I'm not sure about my suggestions on Matching Engine and similar (see comments)

2024-09-10 16:46 UTC, dawnkelly09 commented on .snippets/code/build/fast-transfers/how-to-solver/send-tx-2.js
> +const YOUR_RPC_URL = 'https://your-rpc-url.com';
```suggestion
const YOUR_RPC_URL = 'INSERT_RPC_URL';
```

2024-09-10 16:46 UTC, dawnkelly09 commented on .snippets/code/build/fast-transfers/how-to-solver/send-tx-2.js
> +const MATCHING_ENGINE_PROGRAM_ID = 'Your_MatchingEngine_Program_ID';
```suggestion
const MATCHING_ENGINE_PROGRAM_ID = 'INSERT_MATCHING_ENGINE_PROGRAM_ID';
```

2024-09-10 16:46 UTC, dawnkelly09 commented on .snippets/code/build/fast-transfers/how-to-solver/send-tx-2.js
> +const USDC_MINT_ADDRESS = "Your_USDC_Mint_Address";
```suggestion
const USDC_MINT_ADDRESS = 'INSERT_USDC_MINT_ADDRESS';
```

2024-09-10 16:46 UTC, dawnkelly09 commented on build/contract-integrations/fast-transfers/how-to-solver.md
> +The main difference between [_Participating in an auction_](/build/fast-transfers/how-to-solver/#participating-in-an-auction) and [_Execute fast order to complete auction_](/build/fast-transfers/how-
```suggestion
Participating in an auction is part of the bidding process, where the solver improves their offer to provide the most cost-effective solution and win the right to fulfill the transfer. In comparison, executing a fast order to complete an auction does not involve submitting a new offer price but ensuring the auction winner appropriately processes the transfer. Funds are transferred within the set time frame to finalize the auction and release funds to the user on the target chain. 
```

2024-09-10 16:46 UTC, dawnkelly09 commented on build/contract-integrations/fast-transfers/how-to-solver.md
> +Anyone can post the VAAs on Solana to read and verify VAAs using Wormhole Core Bridge instructions. This is typically done using the [Wormhole TS SDK](https://github.com/wormhole-foundation/wormhole-
```suggestion
Anyone can post the VAAs on Solana to read and verify VAAs using Wormhole Core Bridge instructions. This is typically done using the [Wormhole TS SDK](/build/applications/wormhole-sdk/){target=\_blank}, as shown below:
```

2024-09-10 16:46 UTC, dawnkelly09 commented on build/contract-integrations/fast-transfers/how-to-solver.md
> +## Mainnet Contract Addresses
```suggestion
## MainNet Contract Addresses 
```

2024-09-10 16:46 UTC, dawnkelly09 commented on build/contract-integrations/fast-transfers/how-to-solver.md
> +For mainnet contract addresses for various components of the Fast Transfers protocol, including the Matching Engine, Token Router, and Upgrade Manager refer to the [Mainnet Contract Addresses page.](
```suggestion
For MainNet contract addresses for various components of the Fast Transfers protocol, including the Matching Engine, Token Router, and Upgrade Manager, refer to the [Mainnet Contract Addresses page.](/build/reference/ft-mainnet-addresses/){target=\_blank}
```

2024-09-10 16:46 UTC, dawnkelly09 commented on build/reference/ft-mainnet-addresses.md
> +This section provides the mainnet contract addresses for various components of the Fast Transfers protocol, including the Matching Engine, Token Router, and Upgrade Manager. Each contract is listed w
```suggestion
This section provides the MainNet contract addresses for various components of the Fast Transfers protocol, including the Matching Engine, Token Router, and Upgrade Manager. Each contract is listed with its associated `chainId` and address, ensuring compatibility across multiple blockchain networks.
```

2024-09-10 16:54 UTC, ilariae commented on build/contract-integrations/fast-transfers/how-to-solver.md
> +In [Fast Transfers](/learn/messaging/fast-transfers/){target=\_blank}, solvers ensure efficient cross-chain transfers through a competitive auction process on the Matching Engine. The auction consist
Matching Engine is one of the components of Fast Transfers (Token Router Contracts and Matching Engine), there is a contract but I would call it Matching Engine when talking about it and `MatchingEngine` when referencing the contract not with the backticks everytime 
Maher also called it Matching Engine and they also call it that in their notion pages

2024-09-10 16:56 UTC, ilariae commented on build/contract-integrations/fast-transfers/how-to-solver.md
> +When users interact with Token Routers to transfer assets faster than finality to another chain, they place an order that is processed by the Matching Engine. <!-- link to token routers -->
it's a component of ft so similar answer to before, they are smart contracts components? 
The Token Router determines the type of USDC required on the destination chain while the Matching Engine handles liquidity management and fast transfer auctions

2024-09-10 17:06 UTC, ilariae commented on build/contract-integrations/fast-transfers/how-to-solver.md
> +In [Fast Transfers](/learn/messaging/fast-transfers/){target=\_blank}, solvers ensure efficient cross-chain transfers through a competitive auction process on the Matching Engine. The auction consist
you wont find any reference because there's no documentation besides one notion page so it's up to us to decide I guess but personally I prefer Matching Engine rather than having the backticks every time it's mentioned

2024-09-10 19:08 UTC, dawnkelly09 submitted a review, later dismissed
LGTM

2024-09-10 21:54 UTC, eshaben reviewed
Nice! I left a comment about the snippets. We can reduce the number of snippets and repeat code by using snippet lines. If you have any questions about this, let me know! There is an example on the [tutorials page](https://github.com/wormhole-foundation/wormhole-docs/blob/main/tutorials/messaging/cross-chain-contracts.md?plain=1#L57-L59)

2024-09-10 21:54 UTC, eshaben commented on .snippets/code/build/fast-transfers/how-to-solver/auction-1.js
> +const USDC_MINT_ADDRESS = 'INSERT_USDC_MINT_ADDRESS';
```suggestion
const rpcUrl = 'INSERT_RPC_URL';
const matchingEngineProgramId = 'INSERT_MATCHING_ENGINE_PROGRAM_ID';
const usdcMintAddress = 'INSERT_USDC_MINT_ADDRESS';
```

No need to put the variables into use all uppercase letters, unless they are exported constants. So here they are fine as camel case

2024-09-10 21:54 UTC, eshaben commented on .snippets/code/build/fast-transfers/how-to-solver/auction-1.js
> +const connection = new Connection(YOUR_RPC_URL, "confirmed");
```suggestion
const connection = new Connection(rpcUrl, "confirmed");
```

2024-09-10 21:54 UTC, eshaben commented on .snippets/code/build/fast-transfers/how-to-solver/auction-1.js
> +  USDC_MINT_ADDRESS
```suggestion
  matchingEngineProgramId,
  // EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v on MainNet
  usdcMintAddress 
```

2024-09-10 21:54 UTC, eshaben commented on .snippets/code/build/fast-transfers/how-to-solver/auction-1.js
> +const payer = Keypair.fromSecretKey(...);
do they need to insert a secret key here? is that what the `...` is for?

2024-09-10 21:54 UTC, eshaben commented on .snippets/code/build/fast-transfers/how-to-solver/auction-1.js
> +const feeMicroLamports = yourMethodToDeterminePriorityFee(...);
are these methods they need to create?

2024-09-10 21:54 UTC, eshaben commented on build/contract-integrations/fast-transfers/how-to-solver.md
> +To initiate an auction with this message, complete the following steps on Solana:
```suggestion
To initiate an auction with this message, complete the steps in the following sections on Solana.
```

2024-09-10 21:54 UTC, eshaben commented on build/contract-integrations/fast-transfers/how-to-solver.md
> +The [VAA (Verified Action Approval)](/learn/infrastructure/vaas/){target=\_blank} is a message that acts as an I owe you (IOU) for the solver when the auction is settled. The [Wormhole Spy](/learn/in
Is it referred to as "a relayer engine" like this? I thought the relayer engine was just a starting point for building custom relayers

2024-09-10 21:54 UTC, eshaben commented on build/contract-integrations/fast-transfers/how-to-solver.md
> +To read VAAs on Solana, someone must verify the signatures and post the VAA to a Solana account using the Wormhole Core Bridge. This is done through the [Wormhole TS SDK](https://github.com/wormhole-
the Wormhole Core Contract?

2024-09-10 21:54 UTC, eshaben commented on .snippets/code/build/fast-transfers/how-to-solver/auction-2.js
> +import { Connection, Keypair } from "@solana/web3.js";
This snippet looks like it just builds off of the first one. So what you can do is create one snippet and then in the `how-to-solver.md` file, just reference the lines you want to take from it using this syntax defined here: https://facelessuser.github.io/pymdown-extensions/extensions/snippets/#snippet-lines

This will make it easier to maintain in the future so if something changes, we don't have to update the same code across several files

2024-09-10 21:54 UTC, eshaben commented on .snippets/code/build/fast-transfers/how-to-solver/send-tx-2.js
> +const payer = Keypair.fromSecretKey(...); // Replace [...] with your secret key numbers
yeah, so this should use a variable at the top of the file like the RPC URL does and then add a comment above it saying it is for example purposes only and it is not recommended to store your secret key in a javascript file

2024-09-10 21:54 UTC, eshaben commented on .snippets/code/build/fast-transfers/how-to-solver/auction-1.js
> +import { Connection, Keypair } from "@solana/web3.js";
This file needs to be formatted per the code standards: https://github.com/papermoonio/documentation-style-guide/blob/main/style-guide.md#code-formatting-by-language

There are some double quotes when they should be single and also looks like some spacing issues

2024-09-10 21:54 UTC, eshaben commented on build/contract-integrations/fast-transfers/how-to-solver.md
> +description: Explore how solvers engage in Fast Transfers auctions, from initiating offers to settling, with steps and mainnet contract addresses.
```suggestion
description: Explore how solvers engage in Fast Transfers auctions, from initiating offers to settling, with steps and MainNet contract addresses.
```

2024-09-10 21:54 UTC, eshaben commented on build/contract-integrations/fast-transfers/how-to-solver.md
> +To read VAAs on Solana, someone must verify the signatures and post the VAA to a Solana account using the Wormhole Core Bridge. This is done through the [Wormhole TS SDK](https://github.com/wormhole-
Someone - like as in the developer following this guide?

2024-09-10 21:54 UTC, eshaben commented on build/contract-integrations/fast-transfers/how-to-solver.md
> +this code will for sure fail because there is a bunch of variables that are not being initialized properly like ":Keypair", "MatchingEngineProgram"
Maybe add a `!!! note` explicitly stating they need to initialize these items

2024-09-10 21:54 UTC, eshaben commented on build/contract-integrations/fast-transfers/index.md
> +---
Are you planning on doing this in a separate PR? If you have a lot on your plate, Dawn or I could help out with this

2024-09-10 21:54 UTC, eshaben commented on build/reference/.pages
> + - 'Mainnet Contract Addresses': 'ft-mainnet-addresses.md'
I don't like this, because it's not clear what the difference is between contract adresses and mainnet contract addresses.

I think this should be added to the existing contract addresses page as a section, like how gateway has its own section

2024-09-10 21:54 UTC, eshaben commented on build/reference/ft-mainnet-addresses.md
> +| Component               | chainId | Address                                      | Constructor Arguments            |
```suggestion
| Component               | Chain ID | Address                                      | Constructor Arguments            |
```

2024-09-10 21:54 UTC, eshaben commented on build/reference/ft-mainnet-addresses.md
> +|TokenRouterProxy         | 1       | 28topqjtJzMnPaGFmmZk68tzGmj9W9aMntaEK3QkgtRe |                                  |
So I am assuming these are for Solana?

2024-09-10 21:54 UTC, eshaben commented on build/reference/ft-mainnet-addresses.md
> +|TokenRouterProxy         | 1       | 28topqjtJzMnPaGFmmZk68tzGmj9W9aMntaEK3QkgtRe |                                  |
This table is kind of confusing. There are repeat values like TokenRouterProxy so that is part of the problem.

I'd split these up into subsections with their own tables. I'd also swap out the chain Id for the name of the chain like we do with the other tables.

```
## Fast Transfers

### Solana Hub Contracts (or something?)

Table with Matching Engine Proxy and Upgrade Manager

### Token Router Proxy

### Token Router Implementation
```

Maybe there is a better way to do this like use Token Router Proxy and Token Router Implementation as table headers?

2024-09-10 21:54 UTC, eshaben commented on learn/messaging/.pages
> + - 'Fast Transfers': 'fast-transfers.md'
The `learn/messaging/index.md` page will also need to be updated to add a card on fast transfers

2024-09-11 09:06 UTC, ilariae commented on .snippets/code/build/fast-transfers/how-to-solver/auction-1.js
> +const payer = Keypair.fromSecretKey(...);
yes

2024-09-11 09:11 UTC, ilariae commented on .snippets/code/build/fast-transfers/how-to-solver/auction-1.js
> +const feeMicroLamports = yourMethodToDeterminePriorityFee(...);
yes, for finding the pubkey theres two ways described before the snippet, I'm waiting for details from maher about that, for the fee I think its arbitrary

2024-09-11 09:45 UTC, ilariae commented on build/contract-integrations/fast-transfers/how-to-solver.md
> +The [VAA (Verified Action Approval)](/learn/infrastructure/vaas/){target=\_blank} is a message that acts as an I owe you (IOU) for the solver when the auction is settled. The [Wormhole Spy](/learn/in
yeah they refer to it as relayer engine but it is "a package meant to provide the structure and a starting point for a custom relayer" so I guess we can call it custom relayer 

"The wormhole spy or a custom relayer listen to the Wormhole gossip network to observe the fast VAA." ?

2024-09-11 09:53 UTC, ilariae commented on build/contract-integrations/fast-transfers/index.md
> +---
not really i have kinda been ignoring index pages till now so if you can get to it while I finish the rest that would be great

2024-09-13 15:12 UTC, eshaben reviewed
Few remaining things. Just make sure all of the code snippets are formatted with prettier

2024-09-13 15:12 UTC, eshaben commented on .snippets/code/build/contract-integrations/fast-transfers/how-to-solver/auction.js
> +const feeMicroLamports = yourMethodToDeterminePriorityFee(...);
```suggestion
// Add logic to get the auction's public key. This will be used to initialize the auction
const auction = INSERT_LOGIC_TO_FIND_AUCTION;
// Add logic to determine the priority fee for processing the offer
const feeMicroLamports = INSERT_LOGIC_TO_DETERMINE_FEE;
```

2024-09-13 15:12 UTC, eshaben commented on .snippets/code/build/contract-integrations/fast-transfers/how-to-solver/postVaa.js
> +// below Send Transactions to Verify Signatures and Post VAA
what does this mean?

2024-09-13 16:15 UTC, ilariae commented on .snippets/code/build/contract-integrations/fast-transfers/how-to-solver/postVaa.js
> +// below Send Transactions to Verify Signatures and Post VAA
this was for which sections the code parts belong to, it's not displayed on the website but I don't want the snippets to get confused and messed up in the future since the two parts belong to different sections

2024-09-13 16:31 UTC, eshaben commented on .snippets/code/build/contract-integrations/fast-transfers/how-to-solver/postVaa.js
> +// below Send Transactions to Verify Signatures and Post VAA
They have the same section name, so does that need to be updated?

2024-09-13 16:33 UTC, eshaben commented on .snippets/code/build/contract-integrations/fast-transfers/how-to-solver/postVaa.js
> +// below Send Transactions to Verify Signatures and Post VAA
like Starting an Auction > Send Transactions to Verify Signatures and Post VAA and  Settle Auction with Finalized VAA > Send Transactions to Verify Signatures and Post VAA

2024-09-13 16:33 UTC, eshaben commented on .snippets/code/build/contract-integrations/fast-transfers/how-to-solver/postVaa.js
> +// below Send Transactions to Verify Signatures and Post VAA
I just want to make sure that if someone else edits this file, they'll know what this means

2024-09-13 17:06 UTC, eshaben commented on build/reference/ft-mainnet-addresses.md
> +
This can be deleted now

2024-09-13 17:28 UTC, eshaben approved these changes
LGTM

2024-09-13 17:28 UTC, merged