rev
wormhole-foundation/wormhole-docs pull request #61
Opened 2024-09-06 16:24 UTC by themacexpert

### Description

Adds Demo Repos to the Demos Page and the NTT overview page.

### Checklist

- [x] **Required** - I have added a label to this PR 🏷️
- [ ] **Required** - I have run my changes through Grammarly
- [ ] If pages have been moved, I have created redirects in the `wormhole-mkdocs` repo

2024-09-06 17:06 UTC, dawnkelly09 requested changes
Couple of small things....thank you!

2024-09-06 17:06 UTC, dawnkelly09 commented on build/start-building/demos.md
> +The [Wormhole NTT Connect](https://github.com/wormhole-foundation/demo-ntt-connect){target=\_blank} demo configures a Vite-React Typescript application using the Wormhole Connect SDK and, as an examp
```suggestion
The [Wormhole NTT Connect](https://github.com/wormhole-foundation/demo-ntt-connect){target=\_blank} demo configures a Vite-React TypeScript application using the Wormhole Connect SDK and, as an example, preconfigures the Wormhole Connect Widget to allow transfers between Sepolia and Solana TestNet environments. 
```

2024-09-06 17:06 UTC, dawnkelly09 commented on build/start-building/demos.md
I can't mark it because it's not part of what you changed for this commit but, will you please change xdapp to xDapp (under Scaffolding)?

2024-09-06 17:45 UTC, eshaben commented on learn/messaging/ntt/ntt-overview.md
> +The following example projects demonstrate the use of the Wormhole NTT Framework through Wormhole Connect and the Typescript SDK:
```suggestion
The following example projects demonstrate the use of the Wormhole NTT framework through Wormhole Connect and the TypeScript SDK:
```

2024-09-06 17:47 UTC, eshaben commented on build/start-building/demos.md
> +The [Demo NTT TS SDK Example](https://github.com/wormhole-foundation/demo-ntt-ts-sdk){target=\_blank} demonstrates the use of the Wormhole TS-SDK to facilitate token transfers between different block
```suggestion
The [Demo NTT TS SDK Example](https://github.com/wormhole-foundation/demo-ntt-ts-sdk){target=\_blank} demonstrates the use of the Wormhole TS SDK to facilitate token transfers between different blockchain networks after performing a deployment of the Native Token Transfers framework.
```

2024-09-06 17:47 UTC, eshaben commented on build/start-building/demos.md
> +The [Wormhole NTT Connect](https://github.com/wormhole-foundation/demo-ntt-connect){target=\_blank} demo configures a Vite-React Typescript application using the Wormhole Connect SDK and, as an examp
```suggestion
The [Wormhole NTT Connect](https://github.com/wormhole-foundation/demo-ntt-connect){target=\_blank} demo configures a Vite-React Typescript application using the Wormhole Connect SDK and, as an example, preconfigures the Wormhole Connect widget to allow transfers between Sepolia and Solana TestNet environments. 
```

2024-09-06 19:35 UTC, themacexpert commented
Got a little excited with my CCTP page

2024-09-06 19:37 UTC, themacexpert commented on build/start-building/demos.md
Done

2024-09-06 19:39 UTC, themacexpert commented
thanks for the super speedy reviews @dawnkelly09 @eshaben

2024-09-06 21:22 UTC, eshaben approved these changes
LGTM!

2024-09-10 17:18 UTC, dawnkelly09 approved these changes
thank you!

2024-09-10 22:08 UTC, merged