Ilariae/move gateway
wormhole-foundation/wormhole-docs pull request #64
Opened 2024-09-09 21:07 UTC by ilariae

### Description

- Moved the Gateway Onboarding page from build/chain-integrations/gateway/ to /build/start-building/supported-networks/cosmos/
- Removed old chain-integrations stuff 
- Update all the links I could find
- Renamed cosmwasm to cosmos
- Created an index page for the cosmos section   

### Checklist

- [x] **Required** - I have added a label to this PR 🏷️
- [x] **Required** - I have run my changes through Grammarly
- [ ] If pages have been moved, I have created redirects in the `wormhole-mkdocs` repo

2024-09-10 19:43 UTC, dawnkelly09 requested changes
Just a couple small things. Nice work!

2024-09-10 19:43 UTC, dawnkelly09 commented on build/start-building/supported-networks/cosmos/index.md
> +-   :octicons-code-of-conduct-16:{ .lg .middle } **Cosmos**
```suggestion
-   :octicons-globe-16:{ .lg .middle } **Cosmos**
```
I know it's nitpicky but I like this one better here

2024-09-10 19:43 UTC, dawnkelly09 commented on build/start-building/supported-networks/cosmos/cosmos.md
> +- No webpage, update [here](https://github.com/wormhole-foundation/docs.wormhole.com/blob/main/scripts/src/chains/kujira.json){target=_blank}
```suggestion
- [Website](https://kujira.network/){target=_blank}
```

2024-09-10 19:43 UTC, dawnkelly09 commented on build/start-building/supported-networks/cosmos/cosmos.md
> +- No explorer, update [here](https://github.com/wormhole-foundation/docs.wormhole.com/blob/main/scripts/src/chains/kujira.json){target=_blank}
```suggestion
- [Kujira Finder (explorer)](https://finder.kujira.network/kaiyo-1){target=_blank}
```

2024-09-10 21:57 UTC, eshaben commented on build/start-building/supported-networks/cosmos/cosmos.md
> +- No explorer, update [here](https://github.com/wormhole-foundation/docs.wormhole.com/blob/main/scripts/src/chains/kujira.json){target=_blank}
@dawnkelly09 I'll update this on the supported networks PR I'll be opening (since it's part of the automation stuff)

2024-09-10 22:01 UTC, eshaben reviewed
I initially thought there were some files that still needed to be deleted, but looks like it's all good.

Did you check for snippets? I think there might be some snippets that need to be moved and the file path updated: `'text/build/chain-integrations/gateway/IBCRelayerAllowlistTemplate.md'` and `'code/build/chain-integrations/gateway/gatewayIBCRelayerConfig.toml'`

2024-09-10 22:01 UTC, eshaben commented on build/start-building/supported-networks/cosmos/index.md
> +    [:octicons-arrow-right-16: Start onboarding](/build/chain-integrations/gateway/)
This file should be moved to this section

2024-09-11 13:18 UTC, eshaben submitted a review, later dismissed
LGTM

2024-09-11 18:40 UTC, dawnkelly09 approved these changes
lgtm, thanks!

2024-09-11 18:55 UTC, merged