update core contracts page
wormhole-foundation/wormhole-docs pull request #68
Opened 2024-09-11 13:35 UTC by eshaben

### Description

This creates a basic page for getting started with core contracts. Not super happy with how this turned out, but I don't have the time to keep going with this right now, so I think this is fine as a starting point and we can circle back to it later

### Checklist

- [x] **Required** - I have added a label to this PR 🏷️
- [x] **Required** - I have run my changes through Grammarly

2024-09-11 15:28 UTC, martin0995 submitted a review, later dismissed
It's very clear. Great job!

2024-09-11 16:23 UTC, ilariae requested changes
looks good, just one note and a few suggestions

2024-09-11 16:23 UTC, ilariae commented on build/contract-integrations/core-contracts.md
> +
I would add a redirect to /learn/infrastructure/vaas/#payload-types for the different possible types of payloads

2024-09-11 16:23 UTC, ilariae commented on build/contract-integrations/core-contracts.md
> +
maybe mention keccak256 as the hashing function to sign the message? 
also for working on solana there's this thing to keep in mind ->  the [Solana secp256k1 program](https://docs.solana.com/developing/runtime-facilities/programs#secp256k1-program) will hash the message passed. In this case, the argument for the message should be a single hash of the body, not the twice hashed body.

2024-09-11 16:23 UTC, ilariae commented on build/contract-integrations/core-contracts.md
> +
The VAA digest is separate from the VAA body still relevant. It can be used for replay protection by checking if the digest has already been seen.

2024-09-11 16:23 UTC, ilariae commented on learn/infrastructure/core-contracts.md
> +3. **Message reception and execution** - on the target chain, the Wormhole Core Contract receives the verified message, checks the Guardians' signatures, and executes the corresponding actions, such
2. technically each guardian signs the message individually and when 13 out of 19 have signed it its passed on, they don't wait for the 13 guardians to sign it, each guardian acts on its own, the final signature is a "collection" of the 13 signatures

2024-09-11 16:27 UTC, ilariae commented on learn/infrastructure/core-contracts.md
> +3. **Message reception and execution** - on the target chain, the Wormhole Core Contract receives the verified message, checks the Guardians' signatures, and executes the corresponding actions, such
to be more precise each guardian hashes the body and then the digest to sign it on its own, this is done because the body is deterministically derived from an on chain message. Any two guardians must derive the exact same body. its sort of a check that they do so theres a one to one relationship between VAA's and messages to avoid double processing of messages

2024-09-11 16:28 UTC, ilariae commented on build/contract-integrations/core-contracts.md
> +
this was a rewrite suggestion i havent figured out how to do it so u can commit directly

2024-09-11 17:26 UTC, eshaben commented on build/contract-integrations/core-contracts.md
> +
Hahah is this from Grammarly? I ignored it before, but I can change it 😅

2024-09-11 17:28 UTC, ilariae commented on build/contract-integrations/core-contracts.md
> +
yeah aha the sentence sounded a bit fragmented

2024-09-11 20:26 UTC, dawnkelly09 approved these changes
This is great, Erin! Nice work!

2024-09-12 08:13 UTC, ilariae approved these changes
LGTM!

2024-09-12 19:28 UTC, merged