Ilariae/token bridge
wormhole-foundation/wormhole-docs pull request #96
Opened 2024-09-23 14:08 UTC by ilariae

### Description

Added Build > Contract integrations > Get started with Token bridge page
Heavily updated Learn > Messaging > Token Bridge page

### Checklist

- [x] **Required** - I have added a label to this PR 🏷️
- [x] **Required** - I have run my changes through Grammarly
- [ ] If pages have been moved, I have created redirects in the `wormhole-mkdocs` repo

2024-09-27 01:40 UTC, eshaben reviewed
I only got a little way through and it started looking off to me. This guide should be about creating a contract that interacts with the token bridge directly, instead of JavaScript

2024-09-27 01:40 UTC, eshaben commented on build/contract-integrations/token-bridge.md
> +- **SDK Installation** - Ensure the Wormhole SDK is installed in your project. You can install it via npm or yarn:
```suggestion
- **SDK installation** - ensure the Wormhole SDK is installed in your project. You can install it via npm or yarn:
```

2024-09-27 01:40 UTC, eshaben commented on build/contract-integrations/token-bridge.md
> +- **SDK Installation** - Ensure the Wormhole SDK is installed in your project. You can install it via npm or yarn:
These list items kinda look weird cause of the different formatting. Some lines you summarize with the text in bold, others you don't. I'd just prefer them all to be the same format

2024-09-27 01:40 UTC, eshaben commented on build/contract-integrations/token-bridge.md
> +- **Token attestation** - the token you wish to transfer must be compatible with the destination chain as a wrapped asset. For tokens that do not already exist on the target chain, you must attest th
```suggestion
- **Token attestation** - the token you wish to transfer must be compatible with the destination chain as a wrapped asset. For tokens that do not exist on the target chain, you must attest their details, including metadata like `name`, `symbol`, `decimals`, and `payload_id`, which must be set to `2` for an attestation. This ensures that the wrapped token on the destination chain preserves the original token’s properties. The attestation process records the token's metadata on the target chain to ensure consistency across chains. See the [Attestation section](/docs/learn/infrastructure/vaas/#attestation){target=\_blank} for more details and all the required metadata fields
```

2024-09-27 01:40 UTC, eshaben commented on build/contract-integrations/token-bridge.md
> +- **Verifying wrapped assets** - checking if a token is wrapped and retrieving its original chain and asset details
```suggestion
The Wormhole Token Bridge SDK offers a set of TypeScript types and functions that make it easy to interact with the bridge. The key functionality revolves around:

- **Token transfers** - locking tokens on the source chain and minting wrapped tokens on the destination chain
- **Attestations** - submitting metadata about a token to other chains for wrapping
- **Verifying wrapped assets** - checking if a token is wrapped and retrieving its original chain and asset details
```

2024-09-27 01:40 UTC, eshaben commented on build/contract-integrations/token-bridge.md
> +### Check if a Token is Wrapped
```suggestion
### Check If a Token Is Wrapped
```

2024-09-27 01:40 UTC, eshaben commented on build/contract-integrations/token-bridge.md
> +- **SDK Installation** - Ensure the Wormhole SDK is installed in your project. You can install it via npm or yarn:
Why do they need the SDK? This guide should cover contract to contract interactions, like the Core Contract and CCTP pages

2024-10-01 02:20 UTC, eshaben reviewed
Just reviewed the Learn section content this time around. Huge improvement there! Nice job!

2024-10-01 02:20 UTC, eshaben commented on learn/messaging/token-nft-bridge.md
> +Offering a more efficient, scalable, and secure alternative to traditional solutions, the Token Bridge ensures that assets retain their properties across multiple blockchain ecosystems. Additionally,
```suggestion
Offering a more efficient, scalable, and secure alternative to traditional solutions, the Token Bridge ensures that assets retain their properties across multiple blockchain ecosystems. Additionally, it supports flexible features like [Contract Controlled Transfers](/docs/learn/infrastructure/vaas/#token-transfer-with-message){target=\_blank}, enabling custom interactions by allowing tokens to carry additional data for smart contract integration on the destination chain.
```

2024-10-01 02:20 UTC, eshaben commented on learn/messaging/token-nft-bridge.md
> +In addition to standard token transfers, the Token Bridge supports [Contract Controlled Transfer](/docs/learn/infrastructure/vaas/#token-transfer-with-message){target=\_blank}. This functionality all
I think Contract Controlled Transfer should be plural because it is a type of transfer, and there can be multiple occurrences of this type

2024-10-01 02:20 UTC, eshaben commented on learn/messaging/token-nft-bridge.md
> +3. **Message emission** - a message detailing the transfer is sent through Wormhole’s guardian network, which verifies the transfer and signs the message
```suggestion
3. **Message emission** - a message detailing the transfer is sent through Wormhole’s Guardian Network, which verifies the transfer and signs the message
```

2024-10-01 02:20 UTC, eshaben commented on learn/messaging/token-nft-bridge.md
> +4. **Verification and Minting** - on the destination chain, the transfer message is verified, and wrapped tokens are minted, or native tokens are released from custody
```suggestion
4. **Verification and minting** - on the destination chain, the transfer message is verified, and wrapped tokens are minted, or native tokens are released from custody
```

2024-10-01 02:20 UTC, eshaben commented on learn/messaging/token-nft-bridge.md
> +- `Transfer` - this payload initiates the transfer of tokens, either by minting wrapped tokens or releasing locked tokens
Where do these payloads come from?

2024-10-01 02:20 UTC, eshaben commented on learn/messaging/token-nft-bridge.md
> +- `RegisterChain` - register the token bridge contract (emitter address) for a foreign chain
```suggestion
- `RegisterChain` - register the Token Bridge contract (emitter address) for a foreign chain
```

2024-10-01 02:20 UTC, eshaben commented on learn/messaging/token-nft-bridge.md
> +The [Wormhole guardian network](/docs/learn/infrastructure/guardians/#guardian-network){target=\_blank} plays a critical role in verifying each transfer and ensuring that the message is signed and re
```suggestion
The [Wormhole Guardian Network](/docs/learn/infrastructure/guardians/#guardian-network){target=\_blank} plays a critical role in verifying each transfer and ensuring that the message is signed and relayed securely between chains.
```

2024-10-01 02:20 UTC, eshaben commented on learn/messaging/token-nft-bridge.md
> +The Token Bridge uses an emitter chain and address authorization system to verify the validity of messages. Each token bridge endpoint is registered on its respective chain, ensuring only trusted con
```suggestion
The Token Bridge uses an emitter chain and address authorization system to verify the validity of messages. Each Token Bridge endpoint is registered on its respective chain, ensuring only trusted contracts can send or receive transfer messages.
```

2024-10-01 08:41 UTC, ilariae commented on learn/messaging/token-nft-bridge.md
> +- `Transfer` - this payload initiates the transfer of tokens, either by minting wrapped tokens or releasing locked tokens
https://github.com/wormhole-foundation/wormhole/blob/main/whitepapers/0003_token_bridge.md

2024-10-24 02:09 UTC, eshaben commented
@ilariae putting this into draft mode for now

2024-12-18 15:55 UTC, dawnkelly09 requested changes
These are nice. Don't worry, a lot of these changes are the curved apostrophes ;-)

2024-12-18 15:55 UTC, dawnkelly09 commented on build/contract-integrations/token-bridge.md
> +- **Source Chain Initiation** - `ITokenBridge.transferTokensWithPayload()` is defined in [`ITokenBridge.sol`](https://github.com/wormhole-foundation/wormhole-solidity-sdk/blob/main/src/interfaces/ITo
```suggestion
- **Source Chain Initiation** - `ITokenBridge.transferTokensWithPayload()` is defined in [`ITokenBridge.sol`](https://github.com/wormhole-foundation/wormhole-solidity-sdk/blob/main/src/interfaces/ITokenBridge.sol#L101){target=\_blank}. You can find the underlying logic for logging these payload-carrying transfers in [`Bridge.sol` (`logTransferWithPayload`)](https://github.com/wormhole-foundation/wormhole/blob/main/ethereum/contracts/bridge/Bridge.sol#L336){target=\_blank}
```

2024-12-18 15:55 UTC, dawnkelly09 commented on build/contract-integrations/token-bridge.md
> +    - Ensure the token contract on the source chain implements standard ERC-20 metadata functions (`decimals()`, `symbol()`, `name()`).
```suggestion
    - Ensure the token contract on the source chain implements standard ERC-20 metadata functions (`decimals()`, `symbol()`, `name()`)
```

2024-12-18 15:55 UTC, dawnkelly09 commented on build/contract-integrations/token-bridge.md
> +    - Call `attestToken()` (via the Wormhole SDK or directly on the contract) for the token address.
```suggestion
    - Call `attestToken()` (via the Wormhole SDK or directly on the contract) for the token address
```

2024-12-18 15:55 UTC, dawnkelly09 commented on build/contract-integrations/token-bridge.md
> +    - You don't have to put the token details anywhere in your code. If the token contract is a standard ERC-20, the Token Bridge will read its metadata.
```suggestion
    - You don't have to put the token details anywhere in your code. If the token contract is a standard ERC-20, the Token Bridge will read its metadata
```

2024-12-18 15:55 UTC, dawnkelly09 commented on build/contract-integrations/token-bridge.md
> +    - The attestation may fail or produce incomplete metadata if the token does not implement these standard functions. In that case, you must ensure the token is ERC-20 compliant.
```suggestion
    - The attestation may fail or produce incomplete metadata if the token does not implement these standard functions. In that case, you must ensure the token is ERC-20 compliant
```

2024-12-18 15:55 UTC, dawnkelly09 commented on build/contract-integrations/token-bridge.md
> +const tokenAddress = "<YOUR_TOKEN_ADDRESS>";
```suggestion
const tokenAddress = INSERT_YOUR_TOKEN_ADDRESS;
```

2024-12-18 15:55 UTC, dawnkelly09 commented on build/contract-integrations/token-bridge.md
> +const sender = "<SOURCE_CHAIN_SENDER_ADDRESS>";    // e.g., EVM address
```suggestion
const sender = INSERT_SOURCE_CHAIN_SENDER_ADDRESS;    // e.g., EVM address
```

2024-12-18 15:55 UTC, dawnkelly09 commented on build/contract-integrations/token-bridge.md
> +const recipient = "<TARGET_CHAIN_RECIPIENT_ADDRESS>"; // e.g., Solana address in wormhole format
```suggestion
const recipient = INSERT_TARGET_CHAIN_RECIPIENT_ADDRESS; // e.g., Solana address in wormhole format
```

2024-12-18 15:55 UTC, dawnkelly09 commented on build/contract-integrations/token-bridge.md
> +const tokenAddress = "<SOURCE_CHAIN_TOKEN_ADDRESS>";
```suggestion
const tokenAddress = INSERT_SOURCE_CHAIN_TOKEN_ADDRESS;
```

2024-12-18 15:55 UTC, dawnkelly09 commented on build/contract-integrations/token-bridge.md
> +const receiver = "<YOUR_DESTINATION_CHAIN_ADDRESS>";
```suggestion
const receiver = INSERT_YOUR_DESTINATION_CHAIN_ADDRESS; 
```

2024-12-18 15:55 UTC, dawnkelly09 commented on build/contract-integrations/token-bridge.md
> +const sender = "<SOURCE_CHAIN_SENDER_ADDRESS>";
```suggestion
const sender = INSERT_SOURCE_CHAIN_SENDER_ADDRESS;
```

2024-12-18 15:55 UTC, dawnkelly09 commented on build/contract-integrations/token-bridge.md
> +const recipient = "<TARGET_CHAIN_RECIPIENT_ADDRESS>";
```suggestion
const recipient = INSERT_TARGET_CHAIN_RECIPIENT_ADDRESS;
```

2024-12-18 15:55 UTC, dawnkelly09 commented on build/contract-integrations/token-bridge.md
> +const tokenAddress = "<SOURCE_CHAIN_TOKEN_ADDRESS>";
```suggestion
const tokenAddress = INSERT_SOURCE_CHAIN_TOKEN_ADDRESS;
```

2024-12-18 15:55 UTC, dawnkelly09 commented on build/contract-integrations/token-bridge.md
> +const receiver = "<DESTINATION_CHAIN_CONTRACT_ADDRESS>";
```suggestion
const receiver = INSERT DESTINATION_CHAIN_CONTRACT_ADDRESS;
```

2024-12-18 15:55 UTC, dawnkelly09 commented on build/contract-integrations/token-bridge.md
> +const receiver = "<DESTINATION_CHAIN_ADDRESS>";
```suggestion
const receiver = INSERT_DESTINATION_CHAIN_ADDRESS;
```

2024-12-18 15:55 UTC, dawnkelly09 commented on learn/messaging/token-nft-bridge.md
This page is not showing up in the nav at all. I can get to it if I type in the URL. It needs to be updated on /learn/messaging/.pages please

2024-12-18 15:55 UTC, dawnkelly09 commented on learn/messaging/token-nft-bridge.md
> +Wormhole’s Token Bridge addresses these challenges by providing a decentralized protocol for seamless cross-chain token transfers through a lock-and-mint mechanism. Using Wormhole’s message-passing p
```suggestion
Wormhole's Token Bridge addresses these challenges by providing a decentralized protocol for seamless cross-chain token transfers through a lock-and-mint mechanism. Using Wormhole's message-passing protocol, the Token Bridge allows standards-compliant tokens, like ERC-20 on Ethereum or SPL on Solana, to be transferred between blockchains while preserving their original attributes.
```

2024-12-18 15:55 UTC, dawnkelly09 commented on learn/messaging/token-nft-bridge.md
> +This page introduces the core concepts and functions of Wormhole’s Token Bridge, explaining how it operates, its key features, and how it enables secure and efficient cross-chain token transfers.
```suggestion
This page introduces the core concepts and functions of Wormhole's Token Bridge, explaining how it operates, its key features, and how it enables secure and efficient cross-chain token transfers.
```

2024-12-18 15:55 UTC, dawnkelly09 commented on learn/messaging/token-nft-bridge.md
> +Before a token can be transferred to a new chain, the token’s metadata must be [attested](/docs/learn/infrastructure/vaas/#attestation){target=\_blank}. This process registers the token details (such
```suggestion
Before you can transfer a token to a new chain, the token's metadata must be [attested](/docs/learn/infrastructure/vaas/#attestation){target=\_blank}. This process registers the token details (such as decimals and symbol) on the destination chain, enabling the creation of wrapped assets.
```

2024-12-18 15:55 UTC, dawnkelly09 commented on learn/messaging/token-nft-bridge.md
> +3. **Message emission** - a message detailing the transfer is sent through Wormhole’s Guardian Network, which verifies the transfer and signs the message
```suggestion
3. **Message emission** - a message detailing the transfer is sent through Wormhole's Guardian Network, which verifies the transfer and signs the message
```

2024-12-19 12:51 UTC, ilariae commented on learn/messaging/token-nft-bridge.md
which page are u referring to?

2024-12-19 16:46 UTC, dawnkelly09 reviewed
See my question about the index page card on /build/contract-integrations. If that is happening under a separate PR, then this is ready

2024-12-19 16:46 UTC, dawnkelly09 commented on build/contract-integrations/token-bridge.md
Is adding a card for Token Bridge on /build/contract-integrations/ index page part of this PR or will it be done separately?

2024-12-19 16:46 UTC, dawnkelly09 commented on learn/messaging/token-nft-bridge.md
I think I got confused between the build content and learn content. Disregard!

2024-12-20 15:21 UTC, dawnkelly09 submitted a review, later dismissed
🚀

2024-12-23 13:26 UTC, ilariae commented on build/contract-integrations/.pages
> - - 'FAQs': 'faqs.md'
this is a mistake idk how it got deleted, I added it back

2024-12-23 16:11 UTC, ilariae commented
leaving a comment to remind myself to add the index card for this page

2025-01-13 16:25 UTC, dawnkelly09 requested changes
A few things I noticed. I know @eshaben is still working through this one as well.

2025-01-13 16:25 UTC, dawnkelly09 commented on build/contract-integrations/index.md
Is CCTP not having an index card on this page intentional? If not, please add a card for it. Thank you!

2025-01-13 16:25 UTC, dawnkelly09 commented on build/contract-integrations/token-bridge.md
> +The attestation process doesn’t require you to manually input token details like name, symbol, or decimals. The Token Bridge contract retrieves these values from the token contract itself when you ca
```suggestion
The attestation process doesn't require you to manually input token details like name, symbol, or decimals. The Token Bridge contract retrieves these values from the token contract itself when you call the `attestToken()` method.
```

2025-01-13 16:25 UTC, dawnkelly09 commented on build/contract-integrations/token-bridge.md
> +    First, ensure that you have `Node.js` and `npm` installed on your machine. Then, install the Wormhole SDK packages:
```suggestion
    First, ensure you have `Node.js` and `npm` installed on your machine. Then, install the Wormhole SDK packages:
```

2025-01-13 16:25 UTC, dawnkelly09 commented on build/contract-integrations/token-bridge.md
> +    To use methods like `createAttestation()`, `transfer()`, `redeem()`, and other, you need to instantiate the respective interfaces provided by the SDK. Here's how to set it up in a blockchain-agno
```suggestion
    To use methods like `createAttestation(),` `transfer(),` `redeem(),` and others, you need to instantiate the respective interfaces provided by the SDK. Here's how to set it up in a blockchain-agnostic manner:
```

2025-01-13 16:36 UTC, ilariae commented on build/contract-integrations/index.md
i see the cctp index card is not on the main website either - probably it wasn't there to start with - but I'll make another pr for it because it has nothing to do with the token bridge and things like this keep getting mixed up

2025-03-07 13:12 UTC, ilariae commented
closing this pr since i made a new one for this content

2025-03-07 13:12 UTC, closed without merging